pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - status-success=['Check', 'Test Suite', 'rust code format style check', 'clippy_check']
    actions:
      merge:
        method: rebase

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: ask to format code
    conditions:
      - status-failure=rust code format style check
    actions:
        comment:
          message: This pull request is now not keep same code style as this project. Could you fix it? 🙏 Just run `cargo fmt` to get more details.

  - name: clippy check hint
    conditions:
      - status-failure=clippy_check
    actions:
        comment:
          message: Clippy help us to improve our Rust code. Could you fix it? 🙏 Run `cargo clippy --all-targets --all-features -- -D warnings` to get more details.

  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it? 🙏
      
  - name: say hi on new contribution
    conditions:
      - author!=@rxRust/core-developers
    actions:
        comment:
          message: |
              Welcome to rxRust!
              We're delight to have you onboard <3
