[package]
name = "rxrust"
version = "0.8.3"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"
description = "A Rust implementation of Reactive Extensions."
repository = "https://github.com/rxRust/rxRust"
license="MIT"
keywords = ["reactivex", "rx", "frp"]
categories = ["asynchronous"]
readme = "README.md"
documentation = "https://docs.rs/rxrust/"
homepage = "https://github.com/rxRust/rxRust"
repository = "https://github.com/rxRust/rxRust"

[package.metadata.release]
no-dev-version = true

[dependencies]
futures-preview = "=0.3.0-alpha.18"
lazy_static = "1.3.0"
futures-timer = "0.3.0"
smallvec = "1.1.0"

[dev-dependencies]
float-cmp = "0.5.3"
