[package]
name = "rxrust"
version = "0.8.3"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2018"
description = "A Rust implementation of Reactive Extensions."
repository = "https://github.com/rxRust/rxRust"
documentation = "https://docs.rs/rxrust/"
homepage = "https://github.com/rxRust/rxRust"
license="MIT"
keywords = ["reactivex", "rx", "frp"]
categories = ["asynchronous"]
readme = "README.md"

[package.metadata.release]
no-dev-version = true

[dependencies]
futures-timer = "3.0.2"
smallvec = "1.4.2"

[dependencies.async-std]
version = "1.6.3"
features = ["unstable"]
optional = true

[dependencies.futures]
version="0.3.5"
features= ["thread-pool"]

[dependencies.tokio]
version = "0.2.22"
features = ["rt-threaded", "rt-core"]
optional = true

[features]
default = ["interval", "tokio-scheduler"]
tokio-scheduler = ["tokio"]
interval = ["async-std"]

[dev-dependencies]
float-cmp = "0.8.0"