on: [push, pull_request]
name: test
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rustup override set nightly-2019-09-01
    - name: format style
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
    - name: lint
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
    - name: build
      run: cargo build
    - name: test
      run: cargo test --all
    - name: bench
      run: cargo bench 
